#Configuraciones Locales de ALToque Pago
#Thu Jun 25 12:32:48 PET 2026
empresa.direccion=La Tingui\u00F1a, Ica, Per\u00FA
empresa.razonSocial=Ferreter\u00EDa / Minimarket Huam\u00E1n S.A.C.
empresa.ruc=20000000000
empresa.telefono=000-000000
impresion.impresora=Ninguna
impresion.mensajeTicket=\u00A1Gracias por su compra en ALToque Pago\!
impresion.tama\u00F1oPapel=80mm
kiosko.impresionAuto=true
kiosko.modoOscuro=false
kiosko.sonidoEscaner=true
